package com.keemsa.popularmovies.data;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import net.simonvt.schematic.annotation.Database;
import net.simonvt.schematic.annotation.OnCreate;
import net.simonvt.schematic.annotation.OnUpgrade;
import net.simonvt.schematic.annotation.Table;

/**
 * Created by sebastian on 10/2/16.
 */
@Database(
        version = MovieDatabase.VERSION,
        packageName = "com.keemsa.popularmovies.provider"
)
public class MovieDatabase {
    public static final int VERSION = 2;

    @Table(MovieColumns.class)
    public static final String MOVIE = "movie";

    @Table(TrailerColumns.class)
    public static final String TRAILER = "trailer";

    @Table(ReviewColumns.class)
    public static final String REVIEW = "review";

    @OnCreate
    public static void onCreate(Context context, SQLiteDatabase db) {

    }

    @OnUpgrade
    public static void onUpgrade(Context context, SQLiteDatabase db, int oldVersion, int newVersion) {
        // Drop tables because data is not generated by the user,
        // except fav_movie
        db.execSQL("drop table if exists " + MOVIE);
        db.execSQL("drop table if exists " + TRAILER);
        db.execSQL("drop table if exists " + REVIEW);

        // TODO: Check another alternative for the next code
        db.execSQL(com.keemsa.popularmovies.provider.MovieDatabase.MOVIE);
        db.execSQL(com.keemsa.popularmovies.provider.MovieDatabase.TRAILER);
        db.execSQL(com.keemsa.popularmovies.provider.MovieDatabase.REVIEW);
    }
}
