package com.keemsa.popularmovies.data;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * Created by sebastian on 9/30/16.
 */
public class MovieDbHelper extends SQLiteOpenHelper {

    private static final int DATABASE_VERSION = 1;

    static final String DATABASE_NAME = "movie.db";

    public MovieDbHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {
        final String SQL_CREATE_MOVIE_TABLE =
                "create table " + MovieContract.MovieEntry.TABLE_NAME + " (" +
                        MovieContract.MovieEntry._ID + " integer primary key autoincrement, " +
                        MovieContract.MovieEntry.COlUMN_TITLE + " text not null, " +
                        MovieContract.MovieEntry.COLUMN_SYNOPSIS + " text, " +
                        MovieContract.MovieEntry.COLUMN_POSTER_URL + " text not null, " +
                        MovieContract.MovieEntry.COLUMN_RELEASE_DATE + " integer not null, " +
                        MovieContract.MovieEntry.COLUMN_RATING + " real)";

        sqLiteDatabase.execSQL(SQL_CREATE_MOVIE_TABLE);
    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {
        // Drop the table since the data comes from a server,
        //  it is not generated by the user
        sqLiteDatabase.execSQL("drop table if exists " + MovieContract.MovieEntry.TABLE_NAME);
        onCreate(sqLiteDatabase);
    }
}
